#!/usr/bin/env bash

# `basename` wrapper that applies to positional args, if any, and falls back to reading lines from stdin

if [ $# -gt 0 ]; then
    for arg in "$@"; do
        basename "$arg"
    done
else
    while IFS='$\n' read -r line; do
        basename "$line"
    done
fi
