#!/usr/bin/env bash

# `basename` wrapper that applies to positional args, if any, falling back to stdin lines, and finally the current directory.

if [ $# -gt 0 ]; then
  for arg in "$@"; do
    basename "$arg"
  done
else
  # Call `basename` on each stdin line; if there are none, just call `basename`
  if [ -t 0 ]; then
    basename $PWD
  else
    while IFS= read -r line; do
    basename "$line"
    done
  fi
fi
